### ISSUE TITLE
Config file should be `laravel-settings.php`

### ISSUE THREAD

**Issue by allcaretravels** [bavix/laravel-settings#2]
Hello @rez1dent3,
 
The publish of configuration file should be `laravel-settings.php` or whatever that doesn't conflicts with other packages.

https://github.com/bavix/laravel-settings/blob/893b9954d1bcb4a828721138ec6212050d828736/src/SettingsServiceProvider.php#L29

**Comment by rez1dent3** [comment]
@allcaretravels thanks you. Filename `bavix-settings.php`
